import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Nanum_Gothic } from "next/font/google";
import styles from "./main.module.css";
import "../styles/globals.scss";

import { cx } from "@/libs/utils";
import Footer from "@/components/footer/footer";
import Call from "@/components/call/call";
import Nav from "@/components/nav/nav";
import LastMessage from "@/components/last-message/last-message";

// const inter = Inter({ subsets: ["latin"] });
const nanum = Nanum_Gothic({
  weight: ["400", "700", "800"],
  subsets: ["latin"],
  fallback: ["-apple-system", "BlinkMacSystemFont", "Helvetica Neue", "Apple SD Gothic Neo", "Malgun Gothic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className={cx(nanum.className, styles["max-width"])}>
        <Nav />
        {children}
        <LastMessage />
        <Call />
        <Footer />
      </body>
    </html>
  );
}
